name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/krypton'
      - run: npm install
      - run: npm test